bipproduction/ninox-fox

README.md
Deskripsi:
- membuat dokumentasi readme awal
No Issues
=> doc: tambah readme

.vscode/settings.json, src/app/dashboard/audience/page.tsx, src/app/dashboard/candidate/page.tsx, src/app/dashboard/layout.tsx, src/app/dashboard/leader_trait_assessment/page.tsx, src/app/dashboard/ml-ai/page.tsx, src/app/dashboard/page.tsx, src/app/dashboard/pairing/page.tsx, src/app/dashboard/popularity/page.tsx, src/app/dashboard/public-concern-trend/page.tsx, src/app/dashboard/region-hot-issue/page.tsx, src/app/dashboard/step/page.tsx, src/app/dashboard/swot/page.tsx, src/modules/_global/back/index.ts, src/modules/_global/back/view/layout_view.tsx, src/modules/_global/index.ts
Deskirpsi:
- menambhakan fitur-fitur yang ada di dashboard admin
No Issue
=> style: tambah dashboard admin

src/modules/candidate/back/component/table_candidate.tsx
Deskripsi:
- Update style table list candidate
No Issues
=> style: candidate

src/app/dashboard/popularity/copy/page.tsx, src/app/dashboard/popularity/upload/page.tsx, src/modules/_global/back/view/layout_view.tsx, src/modules/emotion/back/components/copy_data.tsx, src/modules/emotion/back/components/emotion.tsx, src/modules/emotion/back/components/table_data.tsx, src/modules/popularity/back/components/copy_data_popularity.tsx, src/modules/popularity/back/components/popularity.tsx, src/modules/popularity/back/components/table_popularity.tsx, src/modules/popularity/back/components/upload_data_popularity.tsx, src/modules/popularity/back/index.ts, src/modules/popularity/back/val/val_modal_popularity.ts, src/modules/popularity/back/view/view_copy_data_popularity.tsx, src/modules/popularity/back/view/view_popularity.tsx, src/modules/popularity/index.ts
Deskripsi:
- menambahkan copy data popularity
- menamvahkan view popularity
- menambahkan table popularity
- upload data popularity
No issue
=> style: tambah popularity

src/modules/mlai/back/component/component_table.tsx, src/modules/mlai/back/component/table_mlai.tsx, src/modules/step/back/component/component_table_step.tsx, src/modules/step/back/component/table_step.tsx, src/modules/step/back/val/val_step.ts, src/modules/swot/back/component/component_table.tsx, src/modules/swot/back/component/table_swot.tsx
Deskripsi:
- Menambahkan Components Table
- update table step
- update table swot
- update table mlai
No Issue
=> style: tambah components table

src/app/dashboard/(developer)/log-user/page.tsx, src/app/dashboard/(developer)/seeder/page.tsx, src/modules/seeder/index.ts, src/modules/seeder/view/seeder_view.tsx, src/modules/user/log/index.ts, src/modules/user/log/view/user_log_view.tsx
Deskripsi:
- Membuat routing seeder dan log user
- Membuat view seeder dan log user
=> Seeder & log user

prisma/schema.prisma, src/modules/_global/back/view/layout_view.tsx, src/modules/seeder/data/category_leader_trait_assessment.json, src/modules/seeder/data/category_public_concern_trend.json, src/modules/seeder/data/component.json, src/modules/seeder/data/user_role.json
Deskripsi:
- Membuat data seeder json
- Memperbarui key menu dashboard untuk keperluan akses role
- Memperbarui struktur database table componen
No Issues
=> feature : data seeder

prisma/schema.prisma, src/modules/seeder/data/user.json, src/modules/seeder/data/user_access.json, src/modules/seeder/data/user_role.json
Deskripsi:
- Update table database
- Update data seeder user, user access, dan user role
No Issues
=> feature: update data seeder

src/modules/seeder/fun/fun_component.ts, src/modules/seeder/fun/fun_user.ts, src/modules/seeder/fun/fun_user_access.ts, src/modules/seeder/fun/fun_user_role.ts, src/modules/seeder/index.ts, src/modules/seeder/view/seeder_view.tsx
Deskripsi:
- menambahkan seeder components
- menambahkan seeder user access
- menambahkan seeder user role
- menambahkan seeder user
No Issue
=> feat : tambah seeder

prisma/schema.prisma, src/modules/seeder/data/user.json, src/modules/seeder/fun/fun_user.ts
Deskripsi:
- Update struktur table database
- Update data seeder user
- Update fungsi upsert seeder user
No Issues
=> feature: update table database

src/app/dashboard/(admin)/candidate/page.tsx, src/modules/candidate/back/view/list_candidate.tsx
Deskripsi :
- Pencarian wilayah pada halaman candidate dashboard admin
No Issues
=> feature : search in page candidate

prisma/schema.prisma, src/app/dashboard/(admin)/candidate/page.tsx, src/modules/_global/back/view/layout_view.tsx, src/modules/candidate/back/component/modal_add_candidate.tsx, src/modules/candidate/back/component/status_candidate.tsx, src/modules/candidate/back/component/table_candidate.tsx, src/modules/candidate/back/fun/add_candidate.ts, src/modules/candidate/back/fun/get_candidate_by_area.ts, src/modules/candidate/back/view/add_candidate.tsx, src/modules/candidate/back/view/list_candidate.tsx
Deskripsi :
- update struktur database
- backend list data candidate
- backend pencarian list data candidate
- backend add candidate
No Issues
=> feature : backend candidate

src/app/dashboard/(admin)/emotion/page.tsx, src/modules/_global/index.ts, src/modules/candidate/back/fun/get_candidate_active_by_area.ts, src/modules/candidate/back/view/list_candidate.tsx, src/modules/candidate/index.ts, src/modules/emotion/back/view/view_back_emotion.tsx
Deskripsi:
- Update search wilayah pada halaman emotion
No Issues
=> feat : search di halaman emotion

src/app/dashboard/(admin)/audience/page.tsx, src/app/dashboard/(admin)/leader-trait-assessment/page.tsx, src/app/dashboard/(admin)/public-concern-trend/page.tsx, src/app/dashboard/(admin)/region-hot-issue/page.tsx, src/modules/_global/index.ts, src/modules/audience/back/components/table_data_audience.tsx, src/modules/audience/back/fun/get_audience_by_area.ts, src/modules/audience/back/index.ts, src/modules/audience/back/view/view_audience.tsx, src/modules/audience/index.ts, src/modules/leader_trait_assessment/back/components/table_leader.tsx, src/modules/leader_trait_assessment/back/fun/get_lta_by_area.ts, src/modules/leader_trait_assessment/back/view/view_list_leader.tsx, src/modules/leader_trait_assessment/index.ts, src/modules/public_concern_trend/back/components/table_public.tsx, src/modules/public_concern_trend/back/fun/get_pct_by_area.ts, src/modules/public_concern_trend/back/view/view_public.tsx, src/modules/public_concern_trend/index.ts, src/modules/region_hot_issue/back/components/table_region.tsx, src/modules/region_hot_issue/back/fun/get_rhi_by_area.ts, src/modules/region_hot_issue/back/view/view_list_region.tsx, src/modules/region_hot_issue/index.ts
Deskripsi :
- halaman emotion
- halaman pairing
- halaman audience
- halaman leader
- halaman public
- halaman region hot issues
=> Pencarian by area

src/modules/audience/back/components/table_data_audience.tsx, src/modules/leader_trait_assessment/back/components/table_leader.tsx, src/modules/leader_trait_assessment/back/fun/get_lta_by_area.ts, src/modules/leader_trait_assessment/back/view/view_list_leader.tsx, src/modules/public_concern_trend/back/components/table_public.tsx, src/modules/region_hot_issue/back/components/table_region.tsx, src/modules/region_hot_issue/back/fun/get_rhi_by_area.ts, src/modules/region_hot_issue/back/view/view_list_region.tsx, src/modules/seeder/fun/fun_rhi.ts, src/modules/seeder/view/seeder_view.tsx
Deskripsi :
- backend ambil data pada halaman lta
- backend ambil data pada halaman rhi
- membuat seeder value lta
- membuat seeder value rhi
No Issues
=> feat : backend lta dan rhi

src/modules/audience/back/fun/get_audience_by_area.ts, src/modules/audience/back/view/view_audience.tsx, src/modules/candidate/back/component/modal_add_candidate.tsx, src/modules/candidate/back/component/modal_del_candidate.tsx, src/modules/candidate/back/component/modal_edit_candidate.tsx, src/modules/candidate/back/component/table_candidate.tsx, src/modules/candidate/back/view/add_candidate.tsx, src/modules/candidate/back/view/edit_candidate.tsx, src/modules/candidate/back/view/list_candidate.tsx, src/modules/emotion/back/components/copy_data.tsx, src/modules/emotion/back/fun/get_emotion_by_candidate_area_date.ts, src/modules/emotion/back/view/view_back_emotion.tsx, src/modules/leader_trait_assessment/back/view/upload_leader.tsx, src/modules/leader_trait_assessment/back/view/view_list_leader.tsx, src/modules/mlai/back/view/add_mlai.tsx, src/modules/mlai/back/view/list_mlai.tsx, src/modules/pairing/back/components/modal/copy_data_modal.tsx, src/modules/pairing/back/components/pairing.tsx, src/modules/pairing/back/components/table_data_pairing.tsx, src/modules/pairing/back/components/upload_data_pairing.tsx, src/modules/pairing/back/view/view_copy_data_pairing.tsx, src/modules/pairing/back/view/view_pairing.tsx, src/modules/public_concern_trend/back/view/view_public.tsx, src/modules/region_hot_issue/back/view/view_list_region.tsx, src/modules/role_user/components/table_role_user.tsx, src/modules/step/back/view/add_step.tsx, src/modules/step/back/view/list_step.tsx, src/modules/swot/back/view/add_swot.tsx, src/modules/swot/back/view/list_swot.tsx
Deskripsi:
- Ubah menjadi bahasa indonesia
No Issues
=> upd: Update bahasa

src/app/dashboard/(admin)/candidate/add/page.tsx, src/modules/candidate/back/view/add_candidate.tsx
Deskripsi:
- hapus console log dan json stringfy
No Issue
=> upd : hapus console.log

src/app/dashboard/page.tsx, src/modules/_global/fun/fun_provinsi_count.ts, src/modules/_global/home/home.tsx
Deskripsi:
- update codingan untuk di server test
No Issues
=> fix : count di beranda

prisma/schema.prisma, src/modules/seeder/data/component.json, src/modules/seeder/data/user_access.json, src/modules/seeder/fun/fun_component.ts
Deskripsi:
- update struktur db
- update data seeder
=> Amalia :: update 7 des

src/app/seeder-by-pass/route.ts, src/modules/seeder/index.ts
Deskripsi:
- membuat routing seeder by pass
No Issues
=> upd : seeder by pass

src/app/dashboard/layout.tsx, src/app/dashboard/page.tsx, src/modules/_global/back/fun/get_access_admin.ts, src/modules/_global/back/index.ts, src/modules/_global/back/view/layout_view.tsx, src/modules/_global/index.ts, src/modules/auth/fun/get_user_by_cookies.ts, src/modules/auth/index.ts
Deskripsi:
- membuat server action list menu admin
- membuat server action get user by cookies
- mengupdate index _global
No Issues
=> upd: access menu admin

src/app/(dashboard-user)/insights/page.tsx, src/modules/candidate/front/fun/get_all_candidate_front.ts, src/modules/candidate/index.ts, src/modules/user/fun/get_user_area_def_front.ts
Deskripsi:
- membuat server action list cantidate front
- membuat fungsi global
No Issues
=> upd : area default front

src/modules/temporary/ekonomi/components/chart_bangunan_permanen.tsx, src/modules/temporary/ekonomi/components/chart_bangunan_semi_permanen.tsx, src/modules/temporary/infrastruktur_and_transportasi/view/view_infrastruktur_and_transportasi.tsx, src/modules/temporary/kamtibmas/view/view_kamtibmas.tsx, src/modules/temporary/keagamaan/view/view_keagamaan.tsx, src/modules/temporary/kesehatan/view/view_kesehatan.tsx, src/modules/temporary/pendidikan/components/echart_fasilitas_dalam_desa.tsx, src/modules/temporary/pendidikan/components/echart_ketersediaan_transportasi_sma.tsx, src/modules/temporary/pendidikan/components/echart_ketersediaan_transportasi_smk.tsx, src/modules/temporary/pendidikan/components/echart_ketersediaan_transportasi_smp.tsx, src/modules/temporary/pendidikan/components/table_data_guru_honorer.tsx, src/modules/temporary/pendidikan/components/table_data_guru_tersertifikasi.tsx, src/modules/temporary/pendidikan/view/view_pendidikan.tsx, src/modules/temporary/pertanian/view/view_pertanian.tsx
Deskripsi:
- update ekonomi
- update infrastruktur dan transportasi
- update kamtibmas
- update keagamaan
- update kesehatan
- update pendidikan
- update pertanian
No Issue
=> style : update temporary

.gitignore, src/modules/temporary/kamtibmas/view/view_kamtibmas.tsx
Deskripsi:
- update typo
- update gitignore
No Issues
=> upd: typo halaman kamtibmas

src/modules/pairing/front/components/echart_pairing_sentiment.tsx, src/modules/regional_insights/view/view_regional_insights.tsx, src/modules/temporary/ekonomi/components/chart_lembaga_keuangan.tsx, src/modules/temporary/ekonomi/components/chart_tanpa_bangunan_terdekat.tsx, src/modules/temporary/keagamaan/components/echart_rumah_ibadah.tsx, src/modules/temporary/kesehatan/components/echart_akses_fasilitas_kesehatan.tsx, src/modules/temporary/kesehatan/components/echart_jumlah_dokter.tsx, src/modules/temporary/kesehatan/components/echart_pos_pelayanan.tsx, src/modules/temporary/kesehatan/components/echart_rata_kesehatan.tsx, src/modules/temporary/pendidikan/components/echart_jarak_pendidikan.tsx
Deskripsi:
- kelungkung menjadi klungkung
- pasang menjadi pasar
- pemerinta menjadi pemerintah
No Issues
=> upd: perbaiki typo

src/app/dashboard/page.tsx, src/modules/_global/home/components/modal_beranda.tsx, src/modules/_global/home/fan/update_user_area_front.ts, src/modules/_global/home/home.tsx, src/modules/emotion/back/view/view_back_emotion.tsx, src/modules/pairing/back/view/view_pairing.tsx
Deskripsi:
- update default wilayah dan kandidate
- update emotion editor bagian tata letak copy data dan value param
- update data pairing bagian tata letak copy data dan value param
No Issues
=> qc: beranda, emotion editor, data pairing

src/app/dashboard/(developer)/user/page.tsx, src/modules/_global/home/fan/update_user_area_front.ts, src/modules/candidate/back/fun/get_one_candidate.ts, src/modules/candidate/back/view/edit_candidate.tsx, src/modules/candidate/back/view/list_candidate.tsx, src/modules/user/conf/components/modal_edit_conf_user.tsx, src/modules/user/conf/fun/add_conf_user.ts, src/modules/user/conf/fun/get_all_conf_user.ts, src/modules/user/conf/fun/update_conf_user.ts, src/modules/user/conf/view/edit_conf_user.tsx, src/modules/user/conf/view/list_conf_user.tsx
Deskripsi:
- belom selesai nih
=> upd: qx dashboard admin

src/app/(dashboard-user)/ml-ai/page.tsx, src/app/(dashboard-user)/step/page.tsx, src/app/(dashboard-user)/swot/page.tsx, src/modules/mlai/front/fun/get_ml_ai_front.ts
Deskripsi:
- menampilkan data kandidate sesuai dengan kandidate default
- nb: sebelum nya merupakan urutan nama kandidat
No Issues
=> qc : dashboard user

src/modules/temporary/kamtibmas/components/echart_intensitas_pencurian.tsx, src/modules/temporary/kamtibmas/components/echart_kejahatah_penganiayaan.tsx, src/modules/temporary/kamtibmas/components/echart_kejahatan_penipuan.tsx, src/modules/temporary/kamtibmas/components/echart_kejahatan_perkosaan.tsx, src/modules/temporary/kamtibmas/components/echart_pencurian_kekerasan.tsx, src/modules/temporary/kamtibmas/components/echart_peredaran_narkoba.tsx, src/modules/temporary/kamtibmas/view/view_kamtibmas.tsx
Deskripsi:
- 5 grafik pada halaman keamanan atau kamtibnas
No Issues
=> upd: update data sosial ekonomi

src/modules/temporary/kemiskinan_dan_ketimpangan/back/component/table_data_kemiskinan.tsx, src/modules/temporary/kemiskinan_dan_ketimpangan/back/fun/get_data_kemiskinan.ts, src/modules/temporary/kemiskinan_dan_ketimpangan/front/components/echart_presentase_kemiskinan.tsx, src/modules/temporary/kemiskinan_dan_ketimpangan/front/fun/get_data_kemiskinan.ts, src/modules/temporary/kesehatan/back/component/table_rata_rata_jarak_fasilitas.tsx, src/modules/temporary/kesehatan/back/fun/get_rata_rata_jarak_fasilitas.ts, src/modules/temporary/kesehatan/front/components/echart_rata_kesehatan.tsx, src/modules/temporary/kesehatan/front/fun/get_rata_rata_jarak_fasilitas.ts
Deskripsi:
- dashboard admin : perhitungan rata2 pada data kemiskinan dan jarak fasilitas kesehatan
- dashboard user : perhitungan rata2 pada data kemiskinan dan jarak fasilitas kesehatan, tampilan di chart
No Issues
=> upd: data sosial ekonomi = perhitungan

src/modules/emotion/front/fun/get_emotion_chart.ts
Deskripsi:
- order data chart summary by tanggal ascending
No Issues
=> fix: order data chart by tanggal

prisma/schema.prisma, src/modules/mlai/back/component/component_table.tsx, src/modules/mlai/back/component/modal_add_mlai.tsx, src/modules/mlai/back/component/table_mlai.tsx, src/modules/mlai/back/fun/fun_add_mlai.ts, src/modules/mlai/back/fun/fun_edit_mlai.ts, src/modules/mlai/back/fun/fun_get_all_mlai.ts, src/modules/mlai/back/fun/fun_get_one_mlai.ts, src/modules/mlai/back/view/add_mlai.tsx, src/modules/mlai/back/view/edit_mlai.tsx
Deskripsi:
- update struktur database
- update add mlai
- update list mlai
- update edit mlai
No Issues
=> upd: penambahan tgl dan jam pada mlai

src/app/(dashboard-user)/ml-ai/page.tsx, src/modules/mlai/back/fun/fun_add_mlai.ts, src/modules/mlai/front/component/wrapper_read.tsx, src/modules/mlai/front/fun/get_date_ml_ai_front.ts, src/modules/mlai/front/fun/get_ml_ai_front_v2.ts, src/modules/mlai/front/val/val_mlai.ts, src/modules/mlai/front/view/view_ml_ai.tsx, src/modules/mlai/index.ts
Deskripsi:
- koneksi tgl dan jam pada mlai
- list tgl yang ada content nya
- animasi mati saat sudah dibaca
No Issues
=> upd: tgl dan jam pada front mlai

prisma/schema.prisma, src/modules/_global/front/view/layout_view_front.tsx
Deskripsi:
- struktur db table notification
- animasi
No Issues
=> upd : notification center

prisma/schema.prisma, src/app/(dashboard-user)/layout.tsx, src/modules/_global/back/fun/add_notifications.ts, src/modules/_global/front/components/drawer_notifikasi.tsx, src/modules/_global/front/view/layout_view_front.tsx, src/modules/_global/fun/fun_get_one_provinsi.ts, src/modules/_global/fun/get_all_notifications.ts, src/modules/_global/fun/get_count_notifications.ts, src/modules/_global/fun/upd_read_notifications.ts, src/modules/_global/index.ts, src/modules/mlai/back/component/modal_add_mlai.tsx, src/modules/mlai/back/component/modal_edit_mlai.tsx
Deskripsi:
- update design drawer
- fun add notif
No Issues
=> upd: notifikasi

src/modules/emotion/back/components/modal/modal_upload_emotion.tsx, src/modules/leader_trait_assessment/back/components/modal_upload_lta.tsx, src/modules/pairing/back/components/modal/upload_modal.tsx, src/modules/public_concern_trend/back/components/modal_upload_public.tsx, src/modules/region_hot_issue/back/components/modal_edit_rhi.tsx, src/modules/region_hot_issue/back/components/modal_upload_rhi.tsx, src/modules/step/back/component/modal_add_step.tsx, src/modules/step/back/component/modal_edit_step.tsx, src/modules/swot/back/component/modal_add_swot.tsx, src/modules/swot/back/component/modal_edit_swot.tsx
Deskripsi:
- memasang fungsi add notif admin
No Issues
=> upd : add notif admin

src/modules/_global/back/fun/add_notifications.ts, src/modules/_global/front/view/layout_view_front.tsx, src/modules/emotion/back/components/modal/modal_emotion.tsx
Deskripsi:
- fungsi add notif, kategori lain
- menambah add notif pada copy data emotion
No Issues
=> upd: notification

src/app/data-sosial-ekonomi/ekonomi/page.tsx, src/app/data-sosial-ekonomi/infrastruktur-transportasi/page.tsx, src/app/data-sosial-ekonomi/kamtibmas/page.tsx, src/app/data-sosial-ekonomi/keagamaan/page.tsx, src/app/data-sosial-ekonomi/kemiskinan-ketimpangan/page.tsx, src/app/data-sosial-ekonomi/kesehatan/page.tsx, src/app/data-sosial-ekonomi/ketenagakerjaan/page.tsx, src/app/data-sosial-ekonomi/pendidikan/page.tsx, src/app/data-sosial-ekonomi/pertanian/page.tsx, src/modules/temporary/ekonomi/front/view/view_ekonomi.tsx, src/modules/temporary/infrastruktur_and_transportasi/front/view/view_infrastruktur_and_transportasi.tsx, src/modules/temporary/kamtibmas/front/view/view_kamtibmas.tsx, src/modules/temporary/keagamaan/front/view/view_keagamaan.tsx, src/modules/temporary/kemiskinan_dan_ketimpangan/front/view/view_kemiskinan_dan_ketimpangan.tsx, src/modules/temporary/kesehatan/front/view/view_kesehatan.tsx, src/modules/temporary/ketenagakerjaan/front/view/view_ketenagakerjaan.tsx, src/modules/temporary/pendidikan/front/view/view_pendidikan.tsx, src/modules/temporary/pertanian/front/view/view_pertanian.tsx
Deskripsi:
- mengupdate nilai default id provinsi pada data sosial ekonomi
No Issues
=> upd: update datasosial ekonomi

src/app/seeder-by-pass/route.ts
Deskripsi:
- menambahkan seeder provinsi, kabkot, kecamatan, kelurahan dan userAreaDefault pada seeder-by-pass
note: mau diubah pake prisma seeder, error, ga tau kenapa errorr 
No Issues
=> upd:fix seeder by pass

src/modules/_global/home/fan/get_area_kabkot_by_provinsi.ts, src/modules/_global/home/fan/get_area_provinsi.ts
=> upd: fix build

prisma/schema.prisma, src/app/dashboard/(admin)/notifikasi/add/page.tsx, src/app/dashboard/(admin)/notifikasi/page.tsx, src/modules/notifikasi/back/components/modal_add_notifikasi.tsx, src/modules/notifikasi/back/fun/fun_add_notifikasi_back.ts, src/modules/notifikasi/back/fun/fun_get_all_notifikasi_back.ts, src/modules/notifikasi/back/val/data_menu.ts, src/modules/notifikasi/back/val/isModalNotifikasiAlert.ts, src/modules/notifikasi/back/view/view_add_notifikasi.tsx, src/modules/notifikasi/back/view/view_list_notifikasi.tsx, src/modules/notifikasi/index.ts, src/modules/seeder/data/component.json, src/modules/seeder/data/user_access.json, src/modules/user/fun/get_all_admin.ts, src/modules/user/index.ts
Deskripsi :
- manual notifikasi
- add notifikasi
- list notifikasi
No Issues
=> upd: tambah fitur

prisma/schema.prisma, src/app/seeder-by-pass/route.ts, src/modules/_global/back/fun/add_notifications.ts, src/modules/_global/fun/get_all_notifications.ts, src/modules/_global/fun/get_count_notifications.ts, src/modules/notifikasi/back/fun/fun_add_notifikasi_back.ts
Deskripsi:
- update list notifikasi by id user, id candidate dan atau id provinsi
- update struktur database
- update seeder link
No Issues
=> upd: notifikasi dan seeder link

src/modules/candidate/back/fun/add_candidate.ts, src/modules/candidate/back/fun/edit_candidate.ts, src/modules/mlai/back/fun/fun_edit_mlai.ts, src/modules/notifikasi/back/fun/fun_get_all_notifikasi_back.ts, src/modules/seeder/fun/fun_user_access.ts, src/modules/step/back/fun/fun_add_step.ts, src/modules/step/back/fun/fun_edit_step.ts, src/modules/swot/back/fun/fun_add_swot.ts, src/modules/swot/back/fun/fun_edit_swot.ts, src/modules/user/conf/fun/get_all_conf_user.ts, src/modules/user/log/fun/get_log.ts, src/modules/user/role/fun/get_one_role_user.ts, yarn.lock
Deskripsi:
- tiba tiba pas di build error
No Issues
=> fix: update code dan package

src/app/(dashboard-user)/data-learner/page.tsx, src/modules/mlai/front/fun/add_request_mlai.ts, src/modules/mlai/front/fun/get_log_request_mlai_front.ts, src/modules/mlai/front/view/view_data_learner_2.tsx, src/modules/mlai/index.ts
Deskripsi:
- server action add request mlai front
- server action list request mlai front
- pengaplikasian add request
- pengaplikasian list request
No Issues
=> upd: add request mlai

src/app/dashboard/(admin)/ml-ai/page.tsx, src/modules/mlai/back/component/component_table.tsx, src/modules/mlai/back/component/table_mlai.tsx, src/modules/mlai/back/fun/fun_get_all_mlai.ts, src/modules/mlai/back/view/list_mlai.tsx
deskripsi:
- update pagination halaman mlai di dashboard admin
No Issues
=> upd: pagination dashboard admin mlai

src/modules/pairing/front/view/view_pairing.tsx, src/modules/popularity/view/view_popularity.tsx
Deskripsi:
- ganti dari gubernur ke bupati
- di halaman pairing dan popularity
No Issues
=> upd: nama jabatan

src/modules/mlai/front/view/view_data_learner_2.tsx
Deskripsi:
- menambahkan link ke page mlai pada data learner yang sudah terjawab
No Issues
=> upd: link respons mlai

src/modules/pairing/front/view/view_pairing.tsx, src/modules/popularity/view/view_popularity.tsx, src/modules/step/front/view/view_step.tsx, src/modules/swot/front/view/view_swot.tsx
Deskrispi:
- jarak nama
- center image
No Issues
=> upd: jarak nama

src/modules/_global/back/view/layout_view.tsx, src/modules/emotion/front/view/view_summary.tsx, src/modules/mlai/back/component/modal_edit_mlai.tsx, src/modules/mlai/back/fun/fun_add_mlai.ts, src/modules/mlai/front/fun/add_request_mlai.ts
deskripsi:
- update notif admin
- komen notif edit mlai
- update zindex notif di summary
No Issues
=> update : new feature

src/app/(dashboard-user)/summary/page.tsx, src/modules/emotion/back/components/table_data.tsx, src/modules/emotion/back/fun/download_emotion.ts, src/modules/emotion/back/fun/upload_emotion.ts, src/modules/emotion/back/view/view_upload_emotion.tsx, src/modules/emotion/front/component/echart_candidate_summary.tsx, src/modules/emotion/front/component/new_table_top10_dummy.tsx, src/modules/emotion/front/component/new_table_top_10.tsx, src/modules/emotion/front/fun/get_emotion_chart_new.ts, src/modules/emotion/front/fun/get_emotion_persen_new.ts, src/modules/emotion/front/fun/get_emotion_table_new.ts, src/modules/emotion/front/view/view_summary.tsx, src/modules/emotion/index.ts
Deskripsi:
- update tampilan emotion top 10 4 kategori
- koneksi ke database pada emotion terbaru
- dashboard admin download == struktur csv terbaru
- server action upload
- table list dashboard admin emotion
- server action chart emotion 4 kategori
- server action perhitungan persen emotion 4 kategori
No Issues
=> upd: emotion 4 kategori

src/modules/leader_trait_assessment/back/view/view_list_leader.tsx
Deskripsi:
- download file csv ga ada ekstensi file nya jika pada tingkat kabkot
No Issues
=> fix: download lta

src/modules/pairing/front/components/echart_pairing_sentiment.tsx, src/modules/pairing/front/view/view_pairing.tsx
Deskripsi:
- fix bug on page data pasangan regional
- saat pilih wilayah deselected
- error karena server action nya pake yang lama
No Issues
=> fix : data pasangan regional

src/app/(dashboard-user)/summary/page.tsx, src/modules/emotion/front/component/top_pairing_candidate.tsx, src/modules/emotion/front/view/view_summary.tsx
Deskripsi:
- update top pairing candidate
- update view sammary
No issue"
=> style : update emotion

src/modules/regional_insights/view/view_regional_insights.tsx
Deskripsi:
- lupa pakai server action yg baru page :: regional insight
=> upd: new server action

src/modules/_global/front/components/drawer_notifikasi.tsx, src/modules/_global/fun/get_all_notifications.ts
Deskripsi:
- udh bisa saat klik tandai telah dibaca
No Issues
=> upd: load scroll notif

src/app/(dashboard-user)/data-learner/page.tsx, src/modules/mlai/front/fun/get_log_request_mlai_front.ts, src/modules/mlai/front/view/view_data_learner_2.tsx
Deskripsi:
- update scrooll load pada halaman log request saat klik send
No Issues
=> fix : scroll load log request

src/app/(dashboard-user)/data-learner/page.tsx, src/modules/mlai/front/view/view_data_learner_3.tsx, src/modules/mlai/index.ts
Deskripsi:
- update view ml ai data learner 3
No issue
=> feat : update ml ai

src/app/layout.tsx, src/modules/_global/front/components/glitch.tsx, src/modules/_global/front/index.ts, src/modules/_global/index.ts, src/modules/mlai/front/view/view_data_learner_3.tsx, src/modules/regional_insights/view/view_regional_insights.tsx
Deskripsi:
- update ml ai
- update regional insights
- update layout
- add view glitch
No Issue
=> feat : update modules

src/modules/mlai/front/view/view_data_learner_3.tsx, src/modules/pairing/front/view/view_pairing.tsx, src/modules/popularity/view/view_popularity.tsx, src/modules/regional_insights/view/view_regional_insights.tsx
Deskripsi:
- menambahkan icon segitiga pada show more dan hide halaman data learner
- menambahkan glitch putih pada saat notif error
No Issues
=> upd: tambahan
